name: Deployment Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup PHP 8.5 (stable)
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.5'
      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader
      - name: Copy .env File
        run: |
            cp .env.example .env
      - name: Generate Application Key
        run: |
          php artisan key:generate
      - name: Run unit tests
        run: |
            php artisan test --testsuite=Unit

  migrations_and_seeds:
    needs: test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: library-api
           MYSQL_USER: appuser
           MYSQL_PASSWORD: apppass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.5 (stable)
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.5'

      - name: Copy .env File
        env:
            DB_DATABASE: library-api
            DB_USERNAME: appuser
            DB_PASSWORD: apppass
        run: |
            cp .env.example .env
            sed -i 's/DB_DATABASE=.*/DB_DATABASE='"$DB_DATABASE"'/' .env
            sed -i 's/DB_USERNAME=/DB_USERNAME='"$DB_USERNAME"'/' .env
            sed -i 's/DB_PASSWORD=/DB_PASSWORD='"$DB_PASSWORD"'/' .env

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader

      - name: Generate Application Key
        run: |
          php artisan key:generate

      - name: Run Migrations & Seeds
        run: |
            php artisan migrate --force
            php artisan db:seed --force
            
  build-and-push:
    needs: migrations_and_seeds
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            cd /opt/library-api

            echo "Pull latest image"
            docker compose -f docker-compose.prod.yml pull

            echo "Restart containers"
            docker compose -f docker-compose.prod.yml up -d

            echo "Run migrations"
            docker compose -f docker-compose.prod.yml exec -T app php artisan migrate --force

            echo "Run seeds"
            docker compose -f docker-compose.prod.yml exec -T app php artisan db:seed --force

            echo "Optimize caches"
            docker compose -f docker-compose.prod.yml exec -T app php artisan config:cache
            docker compose -f docker-compose.prod.yml exec -T app php artisan route:cache

            echo "Done"
